apiVersion: v1
kind: Service
metadata:
  name: {{ include "echoserver.fullname" . }}
  namespace: {{ include "echoserver.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "echoserver.fullname" . }}
